
export const countryNames: Record<string, string> = {
  'us': 'United States',
  'uk': 'United Kingdom',
  'ca': 'Canada',
  'au': 'Australia',
  'de': 'Germany',
  'fr': 'France',
  'jp': 'Japan',
  'ge': 'Germany',
  'un': 'United States', // Fallback mapping
  'sp': 'Spain',
  'it': 'Italy',
  'br': 'Brazil',
  'mx': 'Mexico',
  'ch': 'China',
  'in': 'India',
  'ru': 'Russia',
  'so': 'South Africa',
  'ar': 'Argentina',
  'sw': 'Switzerland',
  'ne': 'Netherlands',
  'po': 'Poland',
  'se': 'Sweden',
  'no': 'Norway',
  'fi': 'Finland',
  'be': 'Belgium',
  'gr': 'Greece',
  'tu': 'Turkey'
};
