// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymixrcfytvwnghtlabla.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InltaXhyY2Z5dHZ3bmdodGxhYmxhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMDA1MzUsImV4cCI6MjA2MTg3NjUzNX0.w68vQYWAbqBMwSrRFaQRS1bNblSYvrJlRfw5UHCLOzQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);